import { resourceSchema } from "./schemas";

export const resources = [
  {
    name: "Next.js",
    slug: "nextjs",
    category: "Framework",
    description: "React framework for server-rendered, static, and streaming application surfaces.",
    why: "The remake uses it for route-level metadata, server components, image optimization, and Vercel alignment.",
    link: "https://nextjs.org",
    pricing: "Free",
    tags: ["react", "vercel", "performance"],
  },
  {
    name: "shadcn/ui",
    slug: "shadcn-ui",
    category: "UI foundation",
    description: "Copy-owned component foundation built on Radix primitives.",
    why: "It supports source ownership while keeping accessibility primitives close to the codebase.",
    link: "https://ui.shadcn.com",
    pricing: "Free",
    tags: ["radix", "design-system", "accessibility"],
  },
  {
    name: "Pagefind",
    slug: "pagefind",
    category: "Search",
    description: "Static-site search that can be added without a hosted search dependency.",
    why: "A good first search layer for portfolio content before a hosted search system is justified.",
    link: "https://pagefind.app",
    pricing: "Free",
    tags: ["search", "static", "content"],
  },
  {
    name: "Storybook",
    slug: "storybook",
    category: "UI documentation",
    description: "Component workspace for visual states, accessibility checks, and design-system review.",
    why: "Placeholder: expand stories as each final section component lands.",
    link: "https://storybook.js.org",
    pricing: "Free",
    tags: ["components", "a11y", "documentation"],
    status: "draft",
  },
  {
    name: "Playwright",
    slug: "playwright",
    category: "Testing",
    description: "Browser automation for route smoke tests and responsive viewport checks.",
    why: "Draft: used to guard against horizontal overflow and broken navigation while layouts evolve.",
    link: "https://playwright.dev",
    pricing: "Free",
    tags: ["testing", "browser", "responsive"],
    status: "draft",
  },
  {
    name: "Media optimization pipeline",
    slug: "media-optimization-pipeline",
    category: "Media",
    description: "Coming soon: final image/video compression workflow for portfolio media.",
    why: "TBD: replace with the chosen image/video process before launch.",
    link: "https://vercel.com/docs/image-optimization",
    pricing: "TBD",
    tags: ["images", "video", "performance"],
    status: "placeholder",
  },
  // In-browser tools — render at /resources/[slug] via the dynamic
  // registry in src/components/tools/tool-registry.ts. `link` points
  // at a docs source so the card's "source" action still has somewhere
  // to go.
  {
    name: "Contrast Checker",
    slug: "contrast-checker",
    category: "Tool",
    description: "Paste two colors, see WCAG AA / AAA pass-fail for normal and large text with a live sample preview.",
    why: "Every time I tweak a token I want to know whether the pair still clears the accessibility bar — without leaving the page.",
    type: "tool",
    link: "https://www.w3.org/TR/WCAG21/#contrast-minimum",
    pricing: "Free",
    tags: ["a11y", "color", "wcag"],
    status: "ready",
  },
  {
    name: "Color Converter",
    slug: "color-converter",
    category: "Tool",
    description: "Three-way Hex ↔ RGB ↔ HSL converter with a live swatch, lightness shades, and one-click copy.",
    why: "Tailwind v4 token tweaks are easier when the same color reads in every notation at once.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/color_value",
    pricing: "Free",
    tags: ["color", "css", "tokens"],
    status: "ready",
  },
  {
    name: "Shadow Generator",
    slug: "shadow-generator",
    category: "Tool",
    description: "Live box-shadow builder — drag the sliders, copy CSS or a Tailwind arbitrary class. Inset toggle, any CSS color.",
    why: "Shadow stacks are easier to feel than to read, and the Tailwind arbitrary-value syntax is fiddly to type by hand.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow",
    pricing: "Free",
    tags: ["css", "tailwind", "design"],
    status: "ready",
  },
].map((resource) => resourceSchema.parse(resource));
