import { resourceSchema } from "./schemas";

export const resources = [
  {
    name: "Next.js",
    slug: "nextjs",
    category: "Framework",
    description: "React framework for server-rendered, static, and streaming application surfaces.",
    why: "The remake uses it for route-level metadata, server components, image optimization, and Vercel alignment.",
    link: "https://nextjs.org",
    pricing: "Free",
    tags: ["react", "vercel", "performance"],
  },
  {
    name: "shadcn/ui",
    slug: "shadcn-ui",
    category: "UI foundation",
    description: "Copy-owned component foundation built on Radix primitives.",
    why: "It supports source ownership while keeping accessibility primitives close to the codebase.",
    link: "https://ui.shadcn.com",
    pricing: "Free",
    tags: ["radix", "design-system", "accessibility"],
  },
  {
    name: "Pagefind",
    slug: "pagefind",
    category: "Search",
    description: "Static-site search that can be added without a hosted search dependency.",
    why: "A good first search layer for portfolio content before a hosted search system is justified.",
    link: "https://pagefind.app",
    pricing: "Free",
    tags: ["search", "static", "content"],
  },
  {
    name: "Storybook",
    slug: "storybook",
    category: "UI documentation",
    description: "Component workspace for visual states, accessibility checks, and design-system review.",
    why: "Placeholder: expand stories as each final section component lands.",
    link: "https://storybook.js.org",
    pricing: "Free",
    tags: ["components", "a11y", "documentation"],
    status: "draft",
  },
  {
    name: "Playwright",
    slug: "playwright",
    category: "Testing",
    description: "Browser automation for route smoke tests and responsive viewport checks.",
    why: "Draft: used to guard against horizontal overflow and broken navigation while layouts evolve.",
    link: "https://playwright.dev",
    pricing: "Free",
    tags: ["testing", "browser", "responsive"],
    status: "draft",
  },
  {
    name: "Media optimization pipeline",
    slug: "media-optimization-pipeline",
    category: "Media",
    description: "Coming soon: final image/video compression workflow for portfolio media.",
    why: "TBD: replace with the chosen image/video process before launch.",
    link: "https://vercel.com/docs/image-optimization",
    pricing: "TBD",
    tags: ["images", "video", "performance"],
    status: "placeholder",
  },
  // In-browser tools — render at /resources/[slug] via the dynamic
  // registry in src/components/tools/tool-registry.ts. `link` points
  // at a docs source so the card's "source" action still has somewhere
  // to go.
  {
    name: "Contrast Checker",
    slug: "contrast-checker",
    category: "Tool",
    description: "Paste two colors, see WCAG AA / AAA pass-fail for normal and large text with a live sample preview.",
    why: "Every time I tweak a token I want to know whether the pair still clears the accessibility bar — without leaving the page.",
    type: "tool",
    link: "https://www.w3.org/TR/WCAG21/#contrast-minimum",
    pricing: "Free",
    tags: ["css", "color", "a11y", "wcag"],
    status: "ready",
    featured: true,
    iconKey: "Contrast",
  },
  {
    name: "Color Converter",
    slug: "color-converter",
    category: "Tool",
    description: "Three-way Hex ↔ RGB ↔ HSL converter with a live swatch, lightness shades, and one-click copy.",
    why: "Tailwind v4 token tweaks are easier when the same color reads in every notation at once.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/color_value",
    pricing: "Free",
    tags: ["color", "css", "tokens"],
    status: "ready",
  },
  {
    name: "Shadow Generator",
    slug: "shadow-generator",
    category: "Tool",
    description: "Live box-shadow builder — drag the sliders, copy CSS or a Tailwind arbitrary class. Inset toggle, any CSS color.",
    why: "Shadow stacks are easier to feel than to read, and the Tailwind arbitrary-value syntax is fiddly to type by hand.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow",
    pricing: "Free",
    tags: ["css", "tailwind", "design"],
    status: "ready",
  },
  // ── Dev utilities ──────────────────────────────────────────────
  {
    name: "JSON Formatter",
    slug: "json-formatter",
    category: "Tool",
    description: "Pretty-print, validate, and minify JSON in the browser. Indent picker, instant invalid-input feedback.",
    why: "The one tool every API consumer reaches for. Native JSON.parse + stringify, no upload, no server round-trip.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    pricing: "Free",
    tags: ["format", "json", "validate"],
    status: "ready",
    featured: true,
    iconKey: "Braces",
  },
  {
    name: "Base64 Encoder/Decoder",
    slug: "base64",
    category: "Tool",
    description: "Encode text to Base64 or decode it back. UTF-8 safe via TextEncoder/TextDecoder.",
    why: "Pasting binary headers, decoding JWT bodies, dropping images into data URIs — Base64 is the lingua franca.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Glossary/Base64",
    pricing: "Free",
    tags: ["base64", "encode", "decode"],
    status: "ready",
  },
  {
    name: "URL Encoder/Decoder",
    slug: "url-codec",
    category: "Tool",
    description: "Round-trip query strings and path segments through encodeURI / encodeURIComponent.",
    why: "Debugging redirects and OAuth callbacks goes faster when you can see the percent-encoded shape directly.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent",
    pricing: "Free",
    tags: ["url", "encode", "decode"],
    status: "ready",
  },
  {
    name: "JWT Decoder",
    slug: "jwt-decoder",
    category: "Tool",
    description: "Inspect a JWT — header + payload, issued/expiry badges. Decode-only, no verification.",
    why: "Quickly check what claims a token carries without spinning up a curl + Python one-liner.",
    type: "tool",
    link: "https://datatracker.ietf.org/doc/html/rfc7519",
    pricing: "Free",
    tags: ["crypto", "jwt", "auth", "decode"],
    status: "ready",
  },
  {
    name: "UUID Generator",
    slug: "uuid",
    category: "Tool",
    description: "Generate v4 UUIDs via crypto.randomUUID(). Bulk mode up to 500, copy individual rows or the full batch.",
    why: "Seeding fixtures, naming buckets, or stamping migrations — UUIDs you trust without leaving the page.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID",
    pricing: "Free",
    tags: ["uuid", "crypto", "id"],
    status: "ready",
  },
  {
    name: "Password Generator",
    slug: "password-generator",
    category: "Tool",
    description: "Random passwords via crypto.getRandomValues. Tune length, character classes, ambiguous-char avoidance, with a live entropy meter.",
    why: "Local generation only — bytes never leave the browser. The strength bar is informative, not theatrical.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues",
    pricing: "Free",
    tags: ["crypto", "security", "password"],
    status: "ready",
    featured: true,
    iconKey: "KeyRound",
  },
  {
    name: "Hash Generator",
    slug: "hash-generator",
    category: "Tool",
    description: "SHA-1, SHA-256, SHA-384, SHA-512 via SubtleCrypto. Live-updates as you type.",
    why: "Checksumming a string or sanity-checking a server-side hash without reaching for a CLI.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest",
    pricing: "Free",
    tags: ["hash", "crypto", "checksum"],
    status: "ready",
  },
  {
    name: "Pixel ↔ REM Converter",
    slug: "px-rem",
    category: "Tool",
    description: "Convert px ↔ rem / em at a configurable base. Common-size ladder with Tailwind class hints.",
    why: "Reading design specs in px and writing CSS in rem is a daily two-window dance — this collapses it.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/length",
    pricing: "Free",
    tags: ["css", "tailwind", "units"],
    status: "ready",
  },
  {
    name: "String Case Converter",
    slug: "case-converter",
    category: "Tool",
    description: "Convert any string into camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, Title Case, Sentence case, or flat upper/lower.",
    why: "Renaming things across a codebase reads faster when every variant is one click away.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    pricing: "Free",
    tags: ["text", "string", "naming", "rename"],
    status: "ready",
  },
  {
    name: "Slug Generator",
    slug: "slug",
    category: "Tool",
    description: "Turn any text into a URL-safe slug. Strips diacritics, collapses whitespace, picks - or _ separators.",
    why: "Authoring titles for blog posts, projects, or storage keys without hand-rolling the same regex every time.",
    type: "tool",
    link: "https://en.wikipedia.org/wiki/Clean_URL",
    pricing: "Free",
    tags: ["text", "url", "string", "slug"],
    status: "ready",
  },
  {
    name: "Lorem Ipsum",
    slug: "lorem-ipsum",
    category: "Tool",
    description: "Generate paragraphs, sentences, or words of placeholder text. Seeded so the output is stable across rerolls.",
    why: "Filling a layout while real copy is still pending — boring tools should boot instantly.",
    type: "tool",
    link: "https://en.wikipedia.org/wiki/Lorem_ipsum",
    pricing: "Free",
    tags: ["placeholder", "text", "copy"],
    status: "ready",
  },
  {
    name: "Unix Timestamp Converter",
    slug: "timestamp",
    category: "Tool",
    description: "Two-way Unix ↔ ISO converter with UTC, local, milliseconds, and relative time. Live 'now' badge.",
    why: "Reading logs and debugging cron windows without doing math in your head.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    pricing: "Free",
    tags: ["format", "date", "time", "debug"],
    status: "ready",
  },
  {
    name: "Word & Character Counter",
    slug: "word-counter",
    category: "Tool",
    description: "Live count of words, characters, lines, sentences, paragraphs, and an estimated read time.",
    why: "Trimming meta descriptions, social posts, or tweet drafts to a target length.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length",
    pricing: "Free",
    tags: ["text", "writing", "count"],
    status: "ready",
  },
  {
    name: "Number Base Converter",
    slug: "base-converter",
    category: "Tool",
    description: "Convert numbers between binary, octal, decimal, and hex. Underscores + 0x/0o/0b prefixes accepted, BigInt-safe.",
    why: "Bit twiddling and Chmod-style work feels less brittle when you can see every base at once.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt",
    pricing: "Free",
    tags: ["format", "math", "binary", "hex"],
    status: "ready",
  },
  {
    name: "HTML Entity Encoder",
    slug: "html-entities",
    category: "Tool",
    description: "Encode &, <, >, and non-ASCII characters into named or numeric HTML entities. Round-trip decoder too.",
    why: "Embedding code snippets in HTML or escaping copy for an email template without manual find-replace.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Glossary/Entity",
    pricing: "Free",
    tags: ["encode", "html", "entity"],
    status: "ready",
  },
  // ── CSS / design (round 2) ─────────────────────────────────────
  {
    name: "Gradient Generator",
    slug: "gradient",
    category: "Tool",
    description: "Multi-stop linear and radial gradients with live preview, drag-to-reorder stops, and CSS + Tailwind output.",
    why: "Skip the round-trip to Coolors when you just want a quick hero gradient with the project's accent.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/gradient",
    pricing: "Free",
    tags: ["css", "color", "gradient", "design"],
    status: "ready",
    iconKey: "Palette",
  },
  {
    name: "CSS Triangle",
    slug: "css-triangle",
    category: "Tool",
    description: "Border-trick triangle generator. Pick direction, size, and color; copy a ready-to-paste rule.",
    why: "Speech-bubble carets and tooltip arrows show up in every UI; remembering the border hack does not.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/border",
    pricing: "Free",
    tags: ["css", "design", "ui"],
    status: "ready",
  },
  {
    name: "Cubic Bezier Editor",
    slug: "bezier",
    category: "Tool",
    description: "Drag the two control handles, preview the curve, and copy a cubic-bezier() value ready for transition-timing-function.",
    why: "Easings are felt, not read — the curve has to be tunable in place.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function",
    pricing: "Free",
    tags: ["css", "motion", "animation"],
    status: "ready",
  },
  {
    name: "Glassmorphism",
    slug: "glassmorphism",
    category: "Tool",
    description: "Live backdrop-filter preview — blur, saturation, tint, border, radius — with copyable CSS.",
    why: "Frosted-glass cards are a four-property combo; iterating live beats guessing pixel values.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter",
    pricing: "Free",
    tags: ["css", "design", "effect"],
    status: "ready",
  },
  {
    name: "Border Radius",
    slug: "border-radius",
    category: "Tool",
    description: "Four-corner border-radius editor with linked toggle, live preview, and CSS + Tailwind arbitrary-class output.",
    why: "Asymmetric radii are awkward to type out; this makes them point-and-click.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius",
    pricing: "Free",
    tags: ["css", "tailwind", "design"],
    status: "ready",
  },
  {
    name: "Box Model Visualizer",
    slug: "box-model",
    category: "Tool",
    description: "Type margin, border, padding, and content values; see the live box-model render and the computed CSS.",
    why: "Teaching tool plus a fast sanity-check when a layout looks 2px off in the wrong direction.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model",
    pricing: "Free",
    tags: ["css", "layout", "debug"],
    status: "ready",
  },
  {
    name: "Color Palette Extractor",
    slug: "color-palette",
    category: "Tool",
    description: "Drop or upload an image; pull its N most-prominent colors via median-cut quantization. Runs entirely in the browser.",
    why: "Sampling brand colors out of a screenshot without an Adobe round-trip — and the file never leaves the page.",
    type: "tool",
    link: "https://en.wikipedia.org/wiki/Median_cut",
    pricing: "Free",
    tags: ["css", "color", "image", "design"],
    status: "ready",
    iconKey: "Palette",
  },
  // ── Network / reference ────────────────────────────────────────
  {
    name: "UTM Builder",
    slug: "utm-builder",
    category: "Tool",
    description: "Compose UTM-tagged URLs for campaigns. Source, medium, campaign, term, content — auto-encoded, one-click copy.",
    why: "Marketing-grade links should not require remembering five parameter names every time.",
    type: "tool",
    link: "https://en.wikipedia.org/wiki/UTM_parameters",
    pricing: "Free",
    tags: ["encode", "url", "marketing"],
    status: "ready",
  },
  {
    name: "Cron Explainer",
    slug: "cron-explainer",
    category: "Tool",
    description: "Parse a 5-field cron expression and read it back in English. Supports *, ranges, lists, and steps.",
    why: "I shouldn't have to mentally parse `*/15 9-17 * * 1-5` to confirm a schedule.",
    type: "tool",
    link: "https://en.wikipedia.org/wiki/Cron",
    pricing: "Free",
    tags: ["format", "time", "schedule", "debug"],
    status: "ready",
  },
  {
    name: "HTTP Status Lookup",
    slug: "http-status",
    category: "Tool",
    description: "Searchable list of HTTP status codes with class colors, plain-English meanings, and common causes.",
    why: "Quicker than skimming MDN when you just need to remember what 422 actually signals.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status",
    pricing: "Free",
    tags: ["format", "http", "reference", "debug"],
    status: "ready",
  },
  {
    name: "MIME Type Finder",
    slug: "mime-finder",
    category: "Tool",
    description: "Look up MIME types by extension or extensions by MIME type. ~45 of the file types you actually serve.",
    why: "Configuring an Accept header or a static-file server is faster with a short, opinionated list.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types",
    pricing: "Free",
    tags: ["format", "http", "reference"],
    status: "ready",
  },
  {
    name: "Regex Tester",
    slug: "regex-tester",
    category: "Tool",
    description: "Live pattern + flags against a sample buffer. Highlighted matches, capture groups inspector, error messages.",
    why: "The fastest way to know whether your regex actually matches what you think it does.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions",
    pricing: "Free",
    tags: ["format", "text", "regex", "debug"],
    status: "ready",
  },
  // ── Text / data ────────────────────────────────────────────────
  {
    name: "Text Diff",
    slug: "text-diff",
    category: "Tool",
    description: "Line-level diff between two text blocks. LCS-based; additions, deletions, and matches highlighted.",
    why: "Pull-request review without leaving the page — paste before and after, see the change.",
    type: "tool",
    link: "https://en.wikipedia.org/wiki/Longest_common_subsequence_problem",
    pricing: "Free",
    tags: ["text", "diff", "compare"],
    status: "ready",
  },
  {
    name: "CSV ↔ JSON",
    slug: "csv-json",
    category: "Tool",
    description: "Two-way CSV ↔ JSON converter. Proper quote and comma escaping, header row support, downloads or copy.",
    why: "Eyeball a spreadsheet export as objects, or shape a JSON dump into something a non-engineer can open.",
    type: "tool",
    link: "https://datatracker.ietf.org/doc/html/rfc4180",
    pricing: "Free",
    tags: ["format", "csv", "json"],
    status: "ready",
  },
  {
    name: "JSON → TypeScript",
    slug: "json-to-ts",
    category: "Tool",
    description: "Generate a TypeScript interface from any JSON sample. Arrays merge to union members; nested objects get their own types.",
    why: "Bootstrapping types from an unfamiliar API response is the most repeated task in any new integration.",
    type: "tool",
    link: "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html",
    pricing: "Free",
    tags: ["format", "json", "typescript"],
    status: "ready",
  },
  {
    name: "SQL Formatter",
    slug: "sql-formatter",
    category: "Tool",
    description: "Uppercase keywords, break on major clauses, indent sub-blocks. Quick-pass formatter, no AST.",
    why: "A pasted one-line query is unreadable; this gets it 80% of the way to legible without a service round-trip.",
    type: "tool",
    link: "https://en.wikipedia.org/wiki/SQL_syntax",
    pricing: "Free",
    tags: ["format", "sql", "database"],
    status: "ready",
  },
  // ── Generators / fun ───────────────────────────────────────────
  {
    name: "Morse Code",
    slug: "morse",
    category: "Tool",
    description: "Two-way text ↔ Morse converter. International alphabet, `/` between words, single space between letters.",
    why: "The kind of utility that's only needed twice a year — but really needed those two times.",
    type: "tool",
    link: "https://en.wikipedia.org/wiki/Morse_code",
    pricing: "Free",
    tags: ["encode", "text", "morse"],
    status: "ready",
  },
  {
    name: "ASCII Art",
    slug: "ascii-art",
    category: "Tool",
    description: "Render short strings as 5-row block-font ASCII art. Pick the fill character; copy as plaintext.",
    why: "Banners for terminal headers and README hero blocks, without a node CLI install.",
    type: "tool",
    link: "https://en.wikipedia.org/wiki/ASCII_art",
    pricing: "Free",
    tags: ["text", "ascii", "art"],
    status: "ready",
  },
  {
    name: "Roman Numeral Converter",
    slug: "roman",
    category: "Tool",
    description: "Two-way Roman ↔ decimal converter. Validates canonical form (no double subtractive, no rank repetition over 3).",
    why: "Stamping a copyright year is easy; reading MMXXVI in someone else's headline is less so.",
    type: "tool",
    link: "https://en.wikipedia.org/wiki/Roman_numerals",
    pricing: "Free",
    tags: ["format", "text", "number"],
    status: "ready",
  },
  {
    name: "Random Number",
    slug: "random-number",
    category: "Tool",
    description: "Cryptographically unbiased random integers via crypto.getRandomValues with rejection sampling. Bulk + unique modes.",
    why: "Math.random with a modulo is fine for dice; for anything else, you want true uniform sampling.",
    type: "tool",
    link: "https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues",
    pricing: "Free",
    tags: ["crypto", "random", "number"],
    status: "ready",
  },
].map((resource) => resourceSchema.parse(resource));
