import {
  Binary,
  BookOpen,
  Bot,
  Box,
  Braces,
  Cloud,
  Code2,
  Compass,
  Contrast,
  Cpu,
  Crown,
  Database,
  FileText,
  Film,
  Fingerprint,
  Flame,
  GitBranch,
  Globe,
  Hash,
  Image as ImageIcon,
  KeyRound,
  Layers,
  Layout,
  Library,
  LifeBuoy,
  Link2,
  MessageSquare,
  Newspaper,
  Notebook,
  Package,
  Palette,
  PenTool,
  Play,
  Puzzle,
  Rocket,
  Ruler,
  Search,
  Server,
  ShieldCheck,
  Sparkles,
  Square,
  Terminal,
  Trees,
  Triangle,
  Type as TypeIcon,
  Wand2,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Static mapping — keeps the bundle tree-shakable. Add new entries here
// when a new tool's iconKey is set in src/content/resources.ts.
const ICONS: Record<string, LucideIcon> = {
  Binary,
  BookOpen,
  Bot,
  Box,
  Braces,
  Cloud,
  Code2,
  Compass,
  Contrast,
  Cpu,
  Crown,
  Database,
  FileText,
  Film,
  Fingerprint,
  Flame,
  Github: GitBranch,
  Globe,
  Hash,
  Image: ImageIcon,
  KeyRound,
  Layers,
  Layout,
  Library,
  LifeBuoy,
  Link2,
  MessageSquare,
  Newspaper,
  Notebook,
  Package,
  Palette,
  PenTool,
  Play,
  Puzzle,
  Rocket,
  Ruler,
  Search,
  Server,
  ShieldCheck,
  Sparkles,
  Square,
  Terminal,
  Trees,
  Triangle,
  Type: TypeIcon,
  Wand2,
  Wrench,
  Zap,
};

interface ToolIconProps {
  iconKey?: string;
  /** Falls back to a tag-derived guess, then to Wrench. */
  tags?: string[];
  className?: string;
}

// Tag-to-icon fallback when an iconKey isn't set. Ordered by precedence —
// first matching tag wins.
const TAG_FALLBACK: [string, LucideIcon][] = [
  ["color", Palette],
  ["css", Palette],
  ["crypto", ShieldCheck],
  ["security", ShieldCheck],
  ["encode", Code2],
  ["decode", Code2],
  ["format", Braces],
  ["json", Braces],
  ["text", TypeIcon],
  ["string", TypeIcon],
  ["url", Link2],
  ["hash", Fingerprint],
  ["binary", Binary],
  ["math", Binary],
  ["placeholder", Sparkles],
  ["units", Ruler],
  ["ai", Bot],
  ["docs", BookOpen],
  ["reference", BookOpen],
  ["icons", Sparkles],
  ["inspiration", Compass],
  ["design", PenTool],
  ["hosting", Cloud],
  ["infra", Server],
  ["playground", Terminal],
  ["productivity", Zap],
  ["search", Search],
  ["learning", Library],
  ["community", MessageSquare],
  ["open-source", GitBranch],
];

export function ToolIcon({ iconKey, tags = [], className }: ToolIconProps) {
  const Icon =
    (iconKey && ICONS[iconKey]) ||
    TAG_FALLBACK.find(([tag]) => tags.includes(tag))?.[1] ||
    Wrench;
  return <Icon aria-hidden="true" className={className ?? "size-5"} />;
}
